services:
  web:
    build:
      context: .
    command: /usr/bin/env bash -c "exec uvicorn main:main --host 0.0.0.0 --port 8000 --factory"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/web
    depends_on:
      - db
      - redis
    networks:
      - tictactoe

  db:
    image: postgres:latest
    env_file:
      - .env
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    networks:
      - tictactoe

  redis:
    image: redis:alpine
    command:
      - "--requirepass ${REDIS_PASSWORD}"
      - "--appendonly yes"
      - "--appendfilename 'appendonly.aof'"
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - tictactoe

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - tictactoe

networks:
  tictactoe:
    driver: bridge
